name="LOGESH"
age=8
my_adress="BVNMVNBV"
print("my name is:",name)
print("my age is:",age)
print("my adress is:",my_adress)





student="logesh"
subjact="tech"
mark=70
sentence=f'A student name{student}scored{mark}in{subjact}'



data='Bharathwaj|Guduvancherry'
index=data.find('|')
result=data[index+1:len(data)]
print(result)



text= 'From stephen.marquard@ gmail.com Sat Jan  5 09:14:16 2008'
result=data.split(" ")
print("email is",result[2],",", "time is",result[7])